### ISSUE TITLE
Feat: Adding plotting support or not

### ISSUE THREAD

**Issue by germa89** [ansys/pyansys-tools-report#136]
I think the report should include something like:

```output
Plotting support; True/False
```

This can be done with pyvista. Not sure if we want to have such dependency. We should always, extract that part from the library.

**Comment by RobPasMue** [comment]
The ansys-tools-report tool package will require PyVista in any case (as a dependency) so... not sure if we can do this.

**Comment by germa89** [comment]
I do not like having pyvista as a dependency... but I think that kind of information is useful. 

We could do a `try` on `import pyvista` and if successful, just show that line or not.

I would also advocate to extract the code for that check from pyvista.

**Comment by RobPasMue** [comment]
pyvista is a dependency of the package for the GPU check we perform... and we also use scooby which is our main dependency, which also uses pyvista as a dep... so it's going to be almost impossible to "not have" pyvista as a dependency for this package.

**Comment by germa89** [comment]
Ohh.. I misunderstood your comment. 

In that case including a line in the report that says:

```output
Plotting support; True/False
```

should be pretty straight forward because pyvista is already a dependency :)

**Comment by RobPasMue** [comment]
My point is that it will always return ``True`` because it will always be a dependency of the ansys-tools-report package...

**Comment by germa89** [comment]
Oohh..... you are right. Having pyvista equals plot support. My bad.

**Comment by germa89** [comment]
No no.. wait

**Comment by RobPasMue** [comment]
Oh got it... this is something different then.
